name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Ensure reports directory exists
        run: mkdir -p reports

      - name: Run tests
        run: npx mocha --reporter mochawesome --reporter-options reportDir=reports,reportFilename=report_002 --timeout 10000 --verbose

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/

      - name: Display Mocha test results
        if: always()
        run: |
          cat reports/report_002.html || true

      - name: Check for hanging processes
        if: failure()
        run: |
          ps aux

      - name: Cleanup dangling processes
        if: failure()
        run: |
          kill $(ps -e | grep 'node' | awk '{print $1}') || true
